//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgeteerApp1 {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Amp M35 module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.Amp_M35 amp_M35;
        
        /// <summary>The Bluetooth module using socket 6 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Bluetooth bluetooth;
        
        /// <summary>The GPS module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.Seeed.GPS gps;
        
        /// <summary>The Bluetooth module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.Bluetooth bluetooth2;
        
        /// <summary>The Compass module (not connected).</summary>
        private Gadgeteer.Modules.Seeed.Compass compass;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZCerberus Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZCerberus)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZCerberus();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            Microsoft.SPOT.Debug.Print("The module \'amp_M35\' was not connected in the designer and will be null.");
            this.bluetooth = new GTM.GHIElectronics.Bluetooth(6);
            this.gps = new GTM.Seeed.GPS(2);
            Microsoft.SPOT.Debug.Print("The module \'bluetooth2\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'compass\' was not connected in the designer and will be null.");
        }
    }
}
